odel, double>((Expression<Func<HydraulicFractureCompletionModel, double>>) (m => m.FracturePermeability)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<HydraulicFractureCompletionModel, double>((Expression<Func<HydraulicFractureCompletionModel, double>>) (m => m.TotalCompressibility)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<IPRModelJoshiSSViewModel, double>((Expression<Func<IPRModelJoshiSSViewModel, double>>) (m => m.LiquidPICalculated)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<IPRModelJoshiSSViewModel, double>((Expression<Func<IPRModelJoshiSSViewModel, double>>) (m => m.GasPICalculated)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.ReservoirXDim)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.ReservoirYDim)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.PermeabilityX)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.PermeabilityY)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engi
