cyCompletionModel, double>>) (m => m.DamagedZoneThickness)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<PerforationViewModel, double>((Expression<Func<PerforationViewModel, double>>) (m => m.CasingIdCalculated)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.FractureHalfLength)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.FractureWidth)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.FractureProppantPermeability)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.FractureChokePermeability)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.FractureFaceDamagePermeability)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.SpecifiedSkin)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedC
