neering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.PermeabilityZ)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.LocationXPos)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.LocationYPos)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.LocationZPos)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.WellLength)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.WellRw)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.ReservoirExtent)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DistributedCompletionModel, double>((Expression<Func<DistributedCompletionModel, double>>) (m => m.LocationEccen)), PerforationViewModel.TabNumbers.Reservoir);
 
