lb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<FetkovitchEquationModel, double>((Expression<Func<FetkovitchEquationModel, double>>) (m => m.NExponent)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<JonesCompletionModel, double>((Expression<Func<JonesCompletionModel, double>>) (m => m.LiquidCoefficientA)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<JonesCompletionModel, double>((Expression<Func<JonesCompletionModel, double>>) (m => m.LiquidCoefficientB)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<JonesCompletionModel, double>((Expression<Func<JonesCompletionModel, double>>) (m => m.GasCoefficientA)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<JonesCompletionModel, double>((Expression<Func<JonesCompletionModel, double>>) (m => m.GasCoefficientB)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<BackPressureCompletionModel, double>((Expression<Func<BackPressureCompletionModel, double>>) (m => m.ConstantC)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<BackPressureCompletionModel, double>((Expression<Func<BackPressureCompletionModel, double>>) (m => m.SlopeN)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.ReservoirThickness)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Product
