rcyCompletionModel, double>>) (m => m.DamagedZonePermRatio)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.CompletionIntervalRatio)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.CompletionVerticalPermRatio)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.CompactedZoneDiameter)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.CompletionInterval)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.CompletionVerticalPermeability)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<PerforationViewModel, double>((Expression<Func<PerforationViewModel, double>>) (m => m.CompletionDeviationCalculated)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.DamagedZonePermeability)), PerforationViewModel.TabNumbers.Skin);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<Dar
