unc<DarcyCompletionModel, double>>) (m => m.ReservoirArea)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.Time)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.Porosity)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<DarcyCompletionModel, double>((Expression<Func<DarcyCompletionModel, double>>) (m => m.Compressibility)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<ForchheimerCompletionModel, double>((Expression<Func<ForchheimerCompletionModel, double>>) (m => m.CoefficientF)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<ForchheimerCompletionModel, double>((Expression<Func<ForchheimerCompletionModel, double>>) (m => m.CoefficientA)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<HydraulicFractureCompletionModel, double>((Expression<Func<HydraulicFractureCompletionModel, double>>) (m => m.ReservoirRadius)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<HydraulicFractureCompletionModel, double>((Expression<Func<HydraulicFractureCompletionModel, double>>) (m => m.WellboreDiameter)), PerforationViewModel.TabNumbers.Reservoir);
    dictionary.Add(Slb.Production.Engineering.Model.Infrastructure.Expressions.GetPropertyName<HydraulicFractureCompletionM
